knihovna/urls.py
from django.urls import path
# Import pohledů pro zobrazení galerie autorů a detailu autora
from .views import BookDetailView, BooksListView, AuthorsListView, AuthorDetailView, index, BookCreateView, \
    BookUpdateView, BookDeleteView

urlpatterns = [
    # URL adresa pro zobrazení domovské stránky
    path('', index, name='index'),
    # URL adresa pro zobrazení seznamu knih
    path('books/', BooksListView.as_view(), name='books_list'),
    # URL adresa pro zobrazení detailu knihy
    path('books/<int:pk>', BookDetailView.as_view(), name='book_detail'),
    # URL adresa pro zobrazení galerie autorů
    path('authors/', AuthorsListView.as_view(), name='authors_list'),
    # URL adresa pro zobrazení detailu autora
    path('authors/<int:pk>', AuthorDetailView.as_view(), name='author_detail'),
    # URL adresa pro vložení knihy
    path('books/add/', BookCreateView.as_view(), name='book_add'),
    # URL adresa pro aktualizaci knihy
    path('books/<int:pk>/update/', BookUpdateView.as_view(), name='book_update'),
    # URL adresa pro smazání knihy
    path('books/<int:pk>/delete/', BookDeleteView.as_view(), name='book_delete'),
]

mat_knihovna/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from . import settings

urlpatterns = [
    # path('grappelli/', include('grappelli.urls')),  # grappelli URLS
    path('admin/', admin.site.urls),
    path('knihovna/', include('knihovna.urls')),
    path('', RedirectView.as_view(url='knihovna/')),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

knihovna/models.py
# Import třídy User z balíčku django.contrib.auth.models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class Autor(models.Model):
    jmeno = models.CharField(max_length=80, verbose_name='Jméno autora', help_text='Zadejte jméno autora',
                             error_messages={'blank': 'Jméno autora musí být vyplněno'})
    prijmeni = models.CharField(max_length=50, verbose_name='Příjmení autora', help_text='Zadejte příjmení autora',
                                error_messages={'blank': 'Příjmení autora musí být vyplněno'})
    narozeni = models.DateField(blank=True, null=True, verbose_name='Datum narození')
    umrti = models.DateField(blank=True, null=True, verbose_name='Datum úmrtí')
    biografie = models.TextField(blank=True, verbose_name='Životopis')
    fotografie = models.ImageField(upload_to='autori', verbose_name='Fotografie')
    editor = models.ForeignKey(User, on_delete=models.RESTRICT, default=1)

    class Meta:
        ordering = ['prijmeni', 'jmeno']
        verbose_name = 'Autor'
        verbose_name_plural = 'Autoři'

    def __str__(self):
        return f'{self.jmeno} {self.prijmeni}'


class Zanr(models.Model):
    nazev = models.CharField(max_length=20, verbose_name='Název žánru', help_text='Zadejte název žánru')

    class Meta:
        ordering = ['nazev']
        verbose_name = 'Žánr'
        verbose_name_plural = 'Žánry'

    def __str__(self):
        return f'{self.nazev}'


class Vydavatelstvi(models.Model):
    nazev = models.CharField(max_length=100, verbose_name='Název vydavatelství',
                             help_text='Zadejte název vydavatelství',
                             error_messages={'blank': 'Název vydavatelství je povinný údaj'})
    adresa = models.CharField(blank=True, null=True, max_length=200, verbose_name='Adresa')

    class Meta:
        ordering = ['nazev']
        verbose_name = 'Vydavatelství'
        verbose_name_plural = 'Vydavatelství'

    def __str__(self):
        return f'{self.nazev}'


class BookManager(models.Manager):
    def for_user(self, user):
        return self.get_queryset().filter(editor=user)


class Kniha(models.Model):
    titul = models.CharField(max_length=100, verbose_name='Titul knihy', help_text='Zadejte titul knihy',
                             error_messages={'blank': 'Titul knihy musí být vyplněn'})
    autori = models.ManyToManyField(Autor)
    obsah = models.TextField(blank=True, verbose_name='Obsah knihy', help_text='Vložte obsah knihy')
    pocet_stran = models.PositiveIntegerField(blank=True, null=True, validators=[MaxValueValidator(9999)],
                                              verbose_name='Počet stran', help_text='Zadejte počet stran (max. 9999)')
    rok_vydani = models.PositiveIntegerField(blank=True, null=True,
                                             validators=[MinValueValidator(1500), MaxValueValidator(2100)],
                                             verbose_name='Rok vydání', help_text='Zadejte rok vydání (1500 - 2100)')
    obalka = models.ImageField(upload_to='obalky', verbose_name='Obálka knihy')
    zanry = models.ManyToManyField(Zanr)
    editor = models.ForeignKey(User, on_delete=models.RESTRICT, default=1)
    vydavatelstvi = models.ForeignKey('Vydavatelstvi', on_delete=models.CASCADE, blank=True, null=True,
                                      verbose_name='Vydavatelství')

    objects = BookManager()

    class Meta:
        ordering = ['titul']
        verbose_name = 'Kniha'
        verbose_name_plural = 'Knihy'

    def __str__(self):
        return f'{self.titul} ({self.rok_vydani})'


# Vytvoření modelu Recenze
class Recenze(models.Model):
    text = models.TextField(verbose_name='Text recenze', help_text='Vložte text recenze')
    kniha = models.ForeignKey(Kniha, on_delete=models.RESTRICT, verbose_name='Kniha')
    recenzent = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Recenzent')
    HODNOCENI_KNIHY = (
        (0, ''),
        (1, '*'),
        (2, '**'),
        (3, '***'),
        (4, '****'),
        (5, '*****'),
    )
    hodnoceni = models.PositiveSmallIntegerField(verbose_name='Hodnocení', default=3, choices=HODNOCENI_KNIHY)
    upraveno = models.DateTimeField(auto_now=True)

    # Vnitřní třída Meta s dalšími metainformacemi o modelu
    class Meta:
        ordering = ['-hodnoceni']
        verbose_name = 'Recenze'
        verbose_name_plural = 'Recenze'

    # Metoda pro textovou reprezentaci objektu
    def __str__(self):
        return (f'{self.recenzent.last_name if self.recenzent.last_name else self.recenzent}: {self.text}, '
                f'hodnocení: {self.hodnoceni}, ({self.upraveno.strftime("%Y-%m-%d %H:%M:%S")})')

knihovna/forms.py
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Button
from django import forms
from .models import Kniha


class KnihaForm(forms.ModelForm):
    class Meta:
        model = Kniha
        fields = '__all__'
        widgets = {
            'autori': forms.CheckboxSelectMultiple(),
            'zanry': forms.CheckboxSelectMultiple(),
        }


class BookForm(forms.ModelForm):
    class Meta:
        model = Kniha
        fields = ['titul', 'obsah', 'pocet_stran',
                  'rok_vydani', 'autori', 'obalka',
                  'vydavatelstvi', 'zanry']
        widgets = {
            'titul': forms.TextInput(attrs={'class': 'form-control',
                                           'placeholder': 'Zadej titul knihy'}),
            'obsah': forms.Textarea(attrs={'class': 'form-control',
                                           'placeholder': 'Zadej obsah knihy'}),
            'pocet_stran': forms.NumberInput(attrs={'class': 'form-control',
                                           'value': '200', 'min': 10, 'max': 2000}),
            'autori': forms.SelectMultiple(attrs={'class': 'form-control',
                                           'placeholder': 'Zadej jednoho nebo více autorů'}),
            'zanry': forms.SelectMultiple(attrs={'class': 'form-control',
                                           'placeholder': 'Zadej jeden nebo více žánrů'}),
            'vydavatelstvi': forms.Select(attrs={'class': 'form-control',
                                           'placeholder': 'Zadej jedno vydavatelství'}),
            'rok_vydani': forms.NumberInput(attrs={'class': 'form-control',
                                           'value': '2023', 'min': 1000, 'max': 2023}),
            'obalka': forms.ClearableFileInput(attrs={'class': 'form-control',
                                           'placeholder': 'Vlož obrázek'}),
        }
        labels = {
            'titul': 'Titul knihy',
            'obsah': 'Stručný obsah knihy',
            'pocet_stran': 'Počet stran',
            'autori': 'Autoři knih',
            'zanry': 'Žánry',
            'vydavatelstvi': 'Vydavatelství',
            'rok_vydani': 'Vydání',
            'obalka': 'Obálka',
        }
        required = {
            'title': True,
            'obsah': False,
            'pocet_stran': False,
            'autori': True,
            'zanry': False,
            'vydavatelstvi': False,
            'vydani': False,
            'obalka': False,
        }

    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.layout = Layout(
            Fieldset(
                'Informace o knize',
                'titul',
                'obsah',
                'pocet_stran',
                'autori',
                'zanry',
                'vydavatelstvi',
                'rok_vydani',
                'obalka',
            ),
            FormActions(
                ButtonHolder(
                    Submit('submit', 'Uložit', css_class='btn-primary mr-2'),
                    Button('cancel', 'Storno', css_class='btn-secondary',
                           onclick='window.history.back();'),
                    css_class='d-flex'
                )
            ),
        )


class KnihaAdminForm(forms.ModelForm):
    class Meta:
        model = Kniha
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(KnihaAdminForm, self).__init__(*args, **kwargs)
        if not self.instance.editor.is_superuser:
            self.fields['editor'].widget = forms.HiddenInput()
            self.fields['editor'].disabled = True

knihovna/views.py
# Import třídy Count pro agregaci dat
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.db.models import Count
from django.http import HttpResponseRedirect
# Import metody render pro vykreslení šablon
from django.shortcuts import render
from django.urls import reverse_lazy
# Import generických tříd ListView a DetailView z modulu django.views.generic
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .forms import KnihaForm, BookForm
from .models import Kniha, Zanr, Autor


# Pohled pro zobrazení domovské stránky
def index(request):
    zanr = 'povídky'
    context = {
        'nadpis': zanr,
        'knihy': Kniha.objects.order_by('rok_vydani').filter(zanry__nazev=zanr),
        'zanry': Zanr.objects.all()
    }
    return render(request, 'index.html', context=context)


# Přidání třídy BooksListView, která dědí z generické třídy ListView
# Pohled zobrazuje seznam knih
class BooksListView(ListView):
    model = Kniha
    template_name = 'books/books_list.html'
    context_object_name = 'books'
    ordering = ['-rok_vydani']


# Přidání třídy BookDetailView, která dědí z generické třídy DetailView
# Pohled zobrazuje detail knihy
class BookDetailView(DetailView):
    model = Kniha
    template_name = 'books/book_detail.html'
    context_object_name = 'book'


# Přidání třídy BookCreateView, která dědí z generické třídy CreateView
# Pohled zobrazuje formulář pro vložení knihy
class BookCreateView(LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin, CreateView):
    model = Kniha
    # template_name = 'books/book_bootstrap_form.html'
    template_name = 'books/book_form_crispy.html'
    # fields = '__all__'
    form_class = BookForm
    success_url = reverse_lazy('books_list')
    permission_required = ["knihovna.add_kniha"]


# Přidání třídy BookUpdateView, která dědí z generické třídy UpdateView
# Pohled zobrazuje formulář pro aktualizaci knihy
class BookUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Kniha
    template_name = 'books/book_bootstrap_form.html'
    fields = '__all__'
    form = KnihaForm
    context_object_name = 'book'
    success_url = reverse_lazy('books_list')
    permission_required = ["knihovna.change_kniha"]

    def test_func(self):
        kniha = self.get_object()
        return kniha.editor == self.request.user



# Přidání třídy BookDeleteView, která dědí z generické třídy DeleteView
# Pohled zobrazuje formulář pro smazání knihy
class BookDeleteView(LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Kniha
    template_name = 'books/book_confirm_delete.html'
    context_object_name = 'book'
    success_url = reverse_lazy('books_list')
    permission_required = ["knihovna.delete_kniha"]

    def test_func(self):
        kniha = self.get_object()
        return kniha.editor == self.request.user



# Přidání třídy AuthorsListView, která dědí z generické třídy ListView
# Pohled zobrazuje seznam autorů
class AuthorsListView(ListView):
    model = Autor
    context_object_name = 'authors'
    queryset = Autor.objects.annotate(pocet_knih=Count('kniha')).order_by('-pocet_knih')
    template_name = 'authors/authors_list.html'


# Přidání třídy AuthorDetailView, která dědí z generické třídy DetailView
# Pohled zobrazuje detail autora
class AuthorDetailView(DetailView):
    model = Autor
    template_name = 'authors/author_detail.html'
    context_object_name = 'author'

knihovna/templates/books/book_bootstrap_form.html
{% extends 'base.html' %}

{% block title %}Editace knihy{% endblock %}

{% block content %}
    <h1>Editace knihy</h1>
    {# Alternativní formulář s využitím Bootstrapu #}
    <form method="post" enctype="multipart/form-data" class="form">
        {% csrf_token %}
        {% if form.non_field_errors %}
        <div class="alert alert-danger">
            {% for error in form.non_field_errors %}
                <p>{{ error }}</p>
            {% endfor %}
        </div>
        {% endif %}
        <div class="form-group row">
            <label for="id_titul" class="col-sm-2 col-form-label">Název</label>
            <div class="col-sm-10">
                <input type="text" name="titul" maxlength="100" required aria-describedby="id_titul_helptext" id="id_titul" class="form-control" value="{% if not form.titul.value == None %}{{ form.titul.value }}{% endif %}">
                {% if form.titul.errors %}
                    {% for error in form.titul.errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="form-group row">
            <label for="id_autori" class="col-sm-2 col-form-label">Autoři</label>
            <div class="col-sm-10">
                <select name="autori" id="id_autori" class="form-control" multiple>
                    {% for autor in form.fields.autori.queryset %}
                        <option value="{{ autor.pk }}" {% if autor.pk in form.autori.value %}selected{% endif %}>{{ autor }}</option>
                    {% endfor %}
                </select>
                {% if form.autori.errors %}
                    {% for error in form.autori.errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="form-group row">
            <label for="id_obsah" class="col-sm-2 col-form-label">Obsah</label>
            <div class="col-sm-10">
                <textarea name="obsah" rows="10" aria-describedby="id_obsah_helptext" id="id_obsah" class="form-control">{% if not form.titul.value == None %}{{ form.obsah.value }}{% endif %}</textarea>
                {% if form.obsah.errors %}
                    {% for error in form.obsah.errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="form-group row">
            <label for="id_zanry" class="col-sm-2 col-form-label">Žánry</label>
            <div class="col-sm-10">
                <select name="zanry" id="id_zanry" class="form-control" multiple>
                    {% for zanr in form.fields.zanry.queryset %}
                        <option value="{{ zanr.pk }}" {% if zanr.pk in form.zanry.value %}selected{% endif %}>{{ zanr }}</option>
                    {% endfor %}
                </select>
                {% if form.zanry.errors %}
                    {% for error in form.zanry.errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="form-group row">
            <label for="id_rok_vydani" class="col-sm-2 col-form-label">Rok vydání</label>
            <div class="col-sm-10">
                <input type="number" name="rok_vydani" id="id_rok_vydani" aria-describedby="id_pocet_stran_helptext" class="form-control" value="{{ form.rok_vydani.value }}" required>
                {% if form.rok_vydani.errors %}
                    {% for error in form.rok_vydani.errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="form-group row">
            <label for="id_pocet_stran" class="col-sm-2 col-form-label">Počet stran</label>
            <div class="col-sm-10">
                <input type="number" name="pocet_stran" min="0" aria-describedby="id_pocet_stran_helptext" id="id_pocet_stran" class="form-control" value="{{ form.pocet_stran.value }}">
                {% if form.pocet_stran.errors %}
                    {% for error in form.pocet_stran.errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="form-group row">
            <label for="id_vydavatelstvi" class="col-sm-2 col-form-label">Vydavatelství</label>
            <div class="col-sm-10">
                <select name="vydavatelstvi" id="id_vydavatelstvi" class="form-control">
                    {% for value, name in form.fields.vydavatelstvi.choices %}
                        <option value="{{ value }}" {% if form.vydavatelstvi.value == value %}selected{% endif %}>{{ name }}</option>
                    {% endfor %}
                </select>
                {% if form.vydavatelstvi.errors %}
                    {% for error in form.vydavatelstvi.errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        {# Zobrazí obálku, pokud už existuje #}
            <div class="form-group  row">
                <label class="col-sm-2 col-form-label">Obálka</label>
                <div class="col-sm-5">
                    {{ form.obalka }}
                    {% if form.obalka.errors %}
                        {% for error in form.obalka.errors %}
                            <div class="alert alert-danger">{{ error }}</div>
                        {% endfor %}
                    {% endif %}
                </div>
                {% if form.instance.obalka %}
                <div class="col-sm-5">
                    <img src="{{ form.instance.obalka.url }}" alt="Obálka" class="img-thumbnail">
                </div>
                {% endif %}
            </div>
        <div class="form-group row">
            <div class="col-sm-10 offset-sm-2">
                <button type="submit" class="btn btn-primary">Uložit</button>
            </div>
        </div>
    </form>
{% endblock %}

knihovna/templates/books/book_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Smazání knihy{% endblock %}

{% block content %}
    <h1>Smazání knihy</h1>
    <p>Opravdu chcete smazat knihu "{{ book.titul }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit">Ano</button>
    </form>
{% endblock %}

knihovna/templates/books/book_detail.html
{% extends 'base.html' %}

{% block title %}Detail knihy: {{ book.titul }}{% endblock %}

{% block content %}
    <h2 class="display-4 text-center">{{ book.titul }}</h2>
    <div class="row bg-dark p-3 mb-2">
        <div class="col-md-4 text-light">
            {% if book.obalka %}
                <img src="{{ book.obalka.url }}" alt="{{ book }}" class="rounded img-fluid">
            {% endif %}
            <p class="mt-3">Vydáno: {{ book.vydavatelstvi }}, {{ book.rok_vydani }}</p>
            <hr>
            <p>
                {% for autor in book.autori.all %}
                    <a href="{% url 'author_detail' autor.pk %}">{{ autor.jmeno }} {{ autor.prijmeni }}</a>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
            <p>
                {% for zanr in book.zanry.all %}
                    <a href="#" class="btn btn-info">{{ zanr }}</a>
                {% endfor %}
            </p>
        </div>
        <div class="col-md-8">
            <h4 class="text-info">Obsah knihy</h4>
            <p class="text-light">{{ book.obsah }}</p>
        </div>
    </div>
{% endblock %}

knihovna/templates/books/book_form.html
{% extends 'base.html' %}

{% block title %}Editace knihy{% endblock %}

{% block content %}
    <h1>Editace knihy</h1>
    <form method="post" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">Uložit</button>
    </form>
{% endblock %}

knihovna/templates/books/book_form_crispy.html
{% extends 'base.html' %}

{% block content %}
    <h1>Formulář knihy</h1>
    {% load crispy_forms_tags %}
    {% crispy form %}
{% endblock %}

knihovna/templates/books/books_list.html
{% extends 'base.html' %}

{% block title %}Seznam knih{% endblock %}

{% block content %}
  <h2 class="display-4 text-center">Seznam knih</h2>
  <div class="row mb-2">
    <div class="col-12">
    <table class="table table-responsive-lg table-striped table-hover">
      <thead class="bg-secondary">
        <tr>
            <th>Titul</th>
            <th>Autoři</th>
            <th>Vydavatelství</th>
            <th>Rok vydání</th>
            <th>Počet stran</th>
            <th>Akce</th>
        </tr>
      </thead>
      <tbody>
      {% for book in books %}
        <tr>
            <td><strong><a href="{% url 'book_detail' book.pk %}" class="text-info">{{ book.titul.upper }}</a></strong></td>
            <td>
                {% for autor in book.autori.all %}
                <a href="{% url 'author_detail' autor.pk %}">{{ autor.jmeno|first }}. {{ autor.prijmeni }}</a>
                {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </td>
            <td>{{ book.vydavatelstvi }}</td>
            <td class="text-right">{{ book.rok_vydani }}</td>
            <td class="text-right">{{ book.pocet_stran }}</td>
            <td>
                {% if perms.knihovna.change_kniha and user == book.editor %}
                <a href="{% url 'book_update' book.id %}" class="btn btn-primary">Editovat</a>
                {% endif %}
                {% if perms.knihovna.delete_kniha and user == book.editor %}
                <a href="{% url 'book_delete' book.id %}" class="btn btn-danger">Smazat</a>
                {% endif %}
            </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    <p>{{ perms.knihovna }}</p>
    {% if perms.knihovna.add_kniha %}
    <p><a href="{% url 'book_add' %}" class="btn btn-success">Nová kniha</a></p>
    {% endif %}
    </div>
  </div>
{% endblock %}